config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root 'pages#home'
  
  resources :users, only: [:index, :show]
  resources :courts, only: [:index, :show]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  after_validation :geocode
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :location, presence: true

  geocoded_by :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:location])
    end

    def after_sign_in_path_for(resource)
      courts_path
    end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  include CourtsHelper
  before_action :authenticate_user!
  
  def index
    location = "#{current_user.latitude}, #{current_user.longitude}"
    @results = google_api(location)

    @location_arr = [current_user.latitude, current_user.longitude]

    @courts = []
    @results.first(6).each do |result|
      court = {
        name: result["name"],
        lat: result["geometry"]["location"]["lat"],
        long: result["geometry"]["location"]["lng"],
        rating: result["rating"]
      }
      @courts << court
    end
    @courts

    create_court(@courts)

    @locations = []
    @courts.each do |court|
      @locations << [court[:lat], court[:long]]
    end
    @locations
  end

  def show
    @court = Court.find(params[:id])
  end
  
  private 

  def court_params
    params.require(:court).permit(:name, :latitude, :longitude, :details, :rating)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
    def google_api(location) 
        query = "tennis"
        key = ENV["GOOGLE_KEY"]
        location = location
        radius = 2000
        url = "https://maps.googleapis.com/maps/api/place/textsearch/json?query=#{query}&key=#{key}&location=#{location}&radius=#{radius}"
        response = RestClient.get(url)
        parsed = JSON.parse(response)["results"]
    end

    def create_court(array)
        array.each do |court|
            if Court.exists?(name: court[:name])
                next
            else
                Court.create(name: court[:name], latitude: court[:lat], longitude: court[:long], rating: court[:rating], details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." )
            end
        end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courts/index.html.erb
<div class="container">
    <div class="results">
        <% @courts.each do |court| %>
        <div class="card">
            <%= image_tag "tennis" %>
            <div class="card-body">
                <h5 class="card-title"><%= court[:name] %></h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <% court = Court.find_by(name: court[:name]) #temp %> 
                <%= link_to "Select", court_path(court), class: "btn btn-primary" %>
            </div>
        </div>     
        <% end %>
    </div>
    <%= render "components/map" %>
</div>

app/views/courts/show.html.erb
<h1>Here you can see a more details page of a court</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deuce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <% if params["action"] != "home" %>
      <%=  render "shared/navbar" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: url(<%= video_path("tennis") %>)">
    <div class="center">
        <%= link_to "Play!", courts_path, class: "btn btn-success"  %>
        
    </div>
    <%= icon("fas", "chevron-down") %>
</div>

app/views/shared/_navbar.html.erb
<div class="topnav" style="display: flex; justify-content: space-between">
  <div class="static">
    <a class="active" href="#home">Home</a>
    <a href="#news">News</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
  </div>
  <div class="login">
    <% if current_user  %>
      <a href="#"> <%= current_user.email %></a>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>There are <%= @users.count %> players around you!</h1>
<h3>Search bar put location render users in the area 2mi radius</h3>


<% @users.each do |user| %>
<%= user.email %>
<%= user.location %>
<br>
<% end %>